#!/bin/bash

# AJOUTE UNE PERSONNE DANS LE CARNET dates.txt AU FORMAT PRENOM NOM DDN
# variables prenom, nom, ddn
# nb: une phase de pré-traitement doit avoir lieu pour identifier les variables facilement:
# tout espace est comblé par un '_'. ex: 'DE LA VILLEMARQUE' est soumis en tant que 'DE_LA_VILLEMARQUE'
# Ceci devra être pris en compte pour la restitution (tout est traité dans le main)

prenom=$1
nom=$2
ddn=$3
path=$4
destFile="${path}/dates.txt"

nbLinesBefore=$(wc -l ${destFile} | cut -d ' ' -f 1)

if [[ $# -ne 4 ]]; then
	exit 1
else 
	pers="${prenom} ${nom} ${ddn}"

	echo ${pers} >> ${destFile}

	nbLinesAfter=$(wc -l ${destFile} | cut -d ' ' -f 1)
	
	# vérification que la ligne a bien été ajoutée dans la BDD
	if [ "${nbLinesBefore}" != "${nbLinesAfter}" ]; then
		exit 0 # success
	else
		exit 1 # failure
	fi
fi
